backend:
  name: git-gateway
  branch: master

media_folder: src/images
public_folder: images

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Home"
        name: "home"
        fields:
          - { label: "Template Key", name: "templateKey", widget: "hidden", default: "index" }
          - label: "SEO"
            name: "seo"
            widget: "object"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Description", name: "description", widget: "string" }
          - label: "Header"
            name: "header"
            widget: "object"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Sub-Title", name: "subTitle", widget: "string" }
              - { label: "Image", name: "image", widget: "hidden" }
      - file: "src/pages/about.md"
        label: "About"
        name: "about"
        fields:
          - { label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page" }
          - label: "SEO"
            name: "seo"
            widget: "object"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Description", name: "description", widget: "string" }
          - label: "Header"
            name: "header"
            widget: "object"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Sub-Title", name: "subTitle", widget: "string" }
              - { label: "Image", name: "image", widget: "hidden" }
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/blog/index.md"
        label: "Blog"
        name: "blog"
        fields:
          - { label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-page" }
          - { label: "Title", name: "title", widget: "string" }
          - {label: "Body", name: "body", widget: "markdown"}

  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: "true"
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}
